### ISSUE TITLE
Campatibility with Version 10 issues

### ISSUE THREAD

**Issue by FreakyFerrox** [jinkergm/5eFeats#1]
Foundry Compiling log:
setup.js:141 [5eFeats] Metadata validation failed for module "5eFeats": Module Model Validation Errors
[Module.packs]: Model Validation Errors
The Compendium pack "5eFeats" of the "Item" type must declare the "system" upon which it depends.
#logPackageWarnings @ setup.js:141
setup.js:145 [5eFeats] The module "5eFeats" is using "author" which is deprecated in favor of "authors"
#logPackageWarnings @ setup.js:145
setup.js:145 [5eFeats] module "5eFeats" contains the "systems" field which is deprecated in favor of "relationships.systems"
#logPackageWarnings @ setup.js:145
setup.js:145 [5eFeats] The module "5eFeats" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

"systems" converted to "relationships.systems": ["dnd5e", "dnd5eJP"],
and added 
"system": ["dnd5e", "dnd5eJP"],
in section "packs"

{
   "name": "5eFeats",
   "title": "5e Feats",
   "description": "D&D 5e Feats Compendium",
   "relationships.systems": ["dnd5e", "dnd5eJP"],
   "author": "Jinker",
   "version": "0.0.3",
   "minimumCoreVersion": "0.5.0",
   "compatibleCoreVersion": "0.5.5",
   "url": "https://github.com/jinkergm/5eFeats",
   "manifest": "https://raw.githubusercontent.com/jinkergm/5eFeats/master/module.json",
   "download": "https://github.com/jinkergm/5eFeats/archive/master.zip",
   "packs": [
    {
      "name": "5eFeats",
      "label": "5e Feats",
      "path": "feats.db",
	  "system": ["dnd5e", "dnd5eJP"],
      "type": "Item",
      "module": "5eFeats"
    }
  ]
 }
 
 please help me with the rest, I'm not an advanced programmer

**Comment by jinkergm** [comment]
Updated for vf10
